yarnPath: .yarn/releases/yarn-berry.cjs
nodeLinker: node-modules
enableGlobalCache: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
