version: '3.4'

services:
  mysql:
    image: mysql:8.0
    container_name: learning_monorepo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_PORT}:3306
    command:
      - --default-time-zone=+00:00
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
      - --sql-require-primary-key=ON
      - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
